services:
    enginewerk_promas_common.service.date_time_reader_service:
        class: Enginewerk\Promas\CommonBundle\Service\DateTimeReaderService
        public: false
        arguments: ['@enginewerk_promas_common.service.date_time_zone']

    enginewerk_promas_common.service.date_time_zone:
        class: DateTimeZone
        public: false
        arguments:
            - '%app.time_zone%'

    enginewerk_promas_common.uuid.uuid_generator.version_4:
        class: Enginewerk\Common\Uuid\UuidVersion4Generator
        public: false
        arguments:
          - '@enginewerk_promas_common.uuid.adapter.ramsey_uuid_generator'

    enginewerk_promas_common.uuid.adapter.ramsey_uuid_generator:
        public: false
        class: Enginewerk\Common\Uuid\Adapter\RamseyUuidGenerator

    enginewerk_promas_common.logger.monolog_processor.request_handler:
        class: Enginewerk\Promas\CommonBundle\Logger\RequestUuidProcessor
        public: true
        arguments:
          - '@enginewerk_promas_common.uuid.uuid_generator.version_4'
        tags:
            - { name: monolog.processor, method: processRecord }
