Enginewerk\Promas\PropertyBundle\Entity\Investment:
    repositoryClass: Enginewerk\Promas\PropertyBundle\Repository\Doctrine\InvestmentRepository
    type: entity
    table: 'investment'
    id:
        id:
            type: integer
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: string
            length: 41
            column: uuid
            nullable: false
            index: true
            unique: true

        name:
            column: name
            type: string
            nullable: false

        nameCanonical:
            column: name_canonical
            type: string
            nullable: false

        createdAt:
            column: created_at
            type: datetime
            nullable: false

        updatedAt:
            column: updated_at
            type: datetime
            nullable: false

    oneToMany:
        properties:
            targetEntity: Property
            mappedBy: investment
            fetch: EXTRA_LAZY
